version: '3.8'
services: 
  tg-msg-reader:
    build: 
      context: .
    container_name: tg-msg-reader_container
    hostname: tg-msg-reader_container
    env_file:
      - .env
    command: python3 bot.py